Server:
    Listen: "127.0.0.1"
    Port: 8999
    Password: testPwd
Jwt:
  Secret: jwt-token-9824
Mqtt:
  Addr: "tcp://10.10.1.10:1883"
  Topic: "servo"
  ClientID: "mqtt-client"
Door:
  OpenAngle: 130 # 开门角度
  OpenDelay: 1500 # 开门延时